# Generated by Django 3.0.5 on 2021-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demoorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Address', models.TextField()),
                ('Phonenumber', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Image', models.ImageField(upload_to='framesimages')),
                ('Size', models.CharField(max_length=6)),
                ('Width', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
