# Generated by Django 3.0.5 on 2021-07-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PosterName', models.CharField(max_length=50)),
                ('PosterDesc', models.TextField()),
                ('PosterPrice', models.CharField(max_length=10)),
                ('PosterSize', models.CharField(max_length=10)),
                ('PosterImageURL', models.TextField()),
            ],
        ),
    ]
